# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-To-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BACKET_NAME : "ildev-ops-test-bucket"
  EB_APPLICATION_NAME       : "myflask"
  EB_ENVIRONMENT_NAME       : "Myflask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"
  

on:
  push:
    branches: [ main ]
  
jobs:
  my-CI:
    runs-on: ubuntu-latest
   
    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1     # Checkout my project
    
    - name: Create zip deployment package
      run:  zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x "*git*"   # -x - exclude *git* files
      
    - name: Configure my AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id     : ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-access-secret-key : ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region            : ${{ env.AWS_REGION_NAME }}
        
    - name: Copy Deployment package to S3 Bucket
      run:  aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BACKET_NAME }}/
      
    - name: Print Happy Message
      run:  echo "CI Pipeline part Finished successfully"
        
  ####    
      
    
      
    
      
  
