# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-To-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BACKET_NAME : "ildev-ops-test-bucket"
  EB_APPLICATION_NAME       : "myflask"
  EB_ENVIRONMENT_NAME       : "Myflask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"
  

on:
  push:
    branches: [ main ]
  
jobs:
  my-CI:
    runs-on: ubuntu-latest
   
    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1     # Checkout my project
    
    - name: Create zip deployment package
      run:  zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x "*git*"   # -x - exclude *git* files
      
    - name: Configure my AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key : ${{ secrets.AWS_SECRET_KEY }}
        aws-region            : ${{ env.AWS_REGION_NAME }}
        
    - name: Copy Deployment package to S3 Bucket
      run:  aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BACKET_NAME }}/
      
    - name: Print Happy Message for CI
      run:  echo "CI Pipeline part Finished successfully"
        
  ####   
  my-CD:
    runs-on: ubuntu-latest
    needs: [my-CI]
   
    steps:
    - name: Configure my AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key : ${{ secrets.AWS_SECRET_KEY }}
        aws-region            : ${{ env.AWS_REGION_NAME }}
    
    - name: Create new ElasticBeanstalk-App Version
      run: |
        aws elasticbeanstalk create-application-version \
        --application-name ${{ env.EB_APPLICATION_NAME }} \
        --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BACKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
        --version-label "ver-${{ github.sha }}" \
        --description "Commit-SHA-${{ github.sha }}" 
         
    - name: Deploy new ElasticBeanstalk Application version
      run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "ver-${{ github.sha }}"
    
    - name: Print Happy Message for CD
      run:  echo "CD Pipeline part Finished successfully"  
    
      
    
      
  
